### ISSUE TITLE
Windows build fails from time to time

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/base#438]
Looks like there can be some issue in the process of building `base-validating-builders` on Windows, cause it fails to clear the `base\base-validating-builders\build` folder from time to time:

```
20:50:14.535 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.file.UnableToDeleteFileException: Unable to delete directory 'D:\IdeaProjects\Spine\base\base-validating-builders\build'
20:50:14.535 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
20:50:14.536 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   - D:\IdeaProjects\Spine\base\base-validating-builders\build\debug-out.txt
20:50:14.536 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   - D:\IdeaProjects\Spine\base\base-validating-builders\build\error-out.txt
20:50:14.536 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.file.delete.Deleter.throwWithHelpMessage(Deleter.java:145)
20:50:14.536 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.file.delete.Deleter.doDeleteInternal(Deleter.java:88)
20:50:14.536 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.file.delete.Deleter.delete(Deleter.java:78)
20:50:14.536 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.tasks.Delete.clean(Delete.java:78)
```

The second `gradlew clean` run fixes the issue, but maybe we have something in the plugins that actually lock some files? 

Looks like the issue is similar to https://stackoverflow.com/questions/54488100/gradle-failed-to-clean-output-directory

**Comment by alexander-yevsyukov** [comment]
Outdated.
