### ISSUE TITLE
Can Spine merge `desc.ref` files automatically?

### ISSUE THREAD

**Issue by nick-dolgiy** [SpineEventEngine/base#584]
I use Spine `v1.6.0` and want to create an executable shadow jar from my application. I use Gradle and [shadow](https://github.com/johnrengelman/shadow) plugin for this.
When I try to start the application from the shadow jar I get this exception:
```stacktrace
io.spine.type.UnknownTypeException: No Java class found for the Protobuf message of type: spine.system.server.Mirror
        at io.spine.type.TypeName.lambda$type$0(TypeName.java:202)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at io.spine.type.TypeName.type(TypeName.java:202)
        at io.spine.type.TypeName.genericDescriptor(TypeName.java:176)
        at io.spine.type.TypeName.messageDescriptor(TypeName.java:184)
        at io.spine.server.entity.EntityVisibility.of(EntityVisibility.java:114)
        at io.spine.server.entity.model.EntityClass.<init>(EntityClass.java:88)
        at io.spine.server.projection.model.ProjectionClass.<init>(ProjectionClass.java:53)
        at io.spine.server.projection.model.ProjectionClass.lambda$asProjectionClass$0(ProjectionClass.java:63)
        at io.spine.server.model.ClassMap.setEntry(ClassMap.java:108)
        at io.spine.server.model.ClassMap.get(ClassMap.java:88)
        at io.spine.server.model.Model.getClass(Model.java:194)
        at io.spine.server.model.ModelClass.get(ModelClass.java:52)
        at io.spine.server.projection.model.ProjectionClass.asProjectionClass(ProjectionClass.java:63)
        at io.spine.server.projection.ProjectionRepository.toModelClass(ProjectionRepository.java:291)
        at io.spine.server.projection.ProjectionRepository.toModelClass(ProjectionRepository.java:110)
        at io.spine.server.entity.Repository.entityModelClass(Repository.java:156)
        at io.spine.server.entity.Repository.entityClass(Repository.java:177)
        at io.spine.server.projection.ProjectionRepository.createStorage(ProjectionRepository.java:326)
        at io.spine.server.projection.ProjectionRepository.createStorage(ProjectionRepository.java:110)
        at io.spine.server.entity.Repository.storage(Repository.java:308)
        at io.spine.server.entity.Repository.open(Repository.java:281)
        at io.spine.server.entity.Repository.registerWith(Repository.java:217)
        at io.spine.server.entity.DefaultRecordBasedRepository.registerWith(DefaultRecordBasedRepository.java:77)
        at io.spine.server.entity.EventDispatchingRepository.registerWith(EventDispatchingRepository.java:70)
        at io.spine.server.projection.ProjectionRepository.registerWith(ProjectionRepository.java:146)
        at io.spine.server.BoundedContext.registerIfAware(BoundedContext.java:299)
        at io.spine.server.BoundedContext.register(BoundedContext.java:205)
        at io.spine.system.server.SystemContext.registerRepositories(SystemContext.java:85)
        at io.spine.system.server.SystemContext.newInstance(SystemContext.java:73)
        at io.spine.server.BoundedContextBuilder.buildPartial(BoundedContextBuilder.java:615)
        at io.spine.server.BoundedContextBuilder.buildPartial(BoundedContextBuilder.java:605)
        at io.spine.server.BoundedContextBuilder.buildSystem(BoundedContextBuilder.java:591)
        at io.spine.server.BoundedContextBuilder.build(BoundedContextBuilder.java:543)
        ...
```
A solution that solves this problem is to configure merging `desc.ref` files on the stage of assembling the shadow jar.
With the shadow plugin I use it looks like this:
```groovy
shadowJar {
  mergeServiceFiles {
    path = 'desc.ref'
  }
}
```
Can Spine framework do something to let end-users avoid this manual configuration?

**Comment by armiol** [comment]
@nick-dolgiy this isn't the right place to ask questions. Please use https://github.com/SpineEventEngine/feedback for these matters. Let's move the issue there and then discuss. Closing it here.

@dmdashenkov could you please take a look at the issue itself, while Nick is moving things around?

**Comment by nick-dolgiy** [comment]
Moved to https://github.com/SpineEventEngine/feedback/issues/6
